version: "3.7"
services:
#  app:
#    container_name: go_api_app
#    build: .
#    ports:
#      - '8081:8081'
#    restart: on-failure
#    volumes:
#      - app:/var/lib/app
#    depends_on:
#      - go_database_pg
#    networks:
#      - go_networks

  go_database_pg:
    image: postgres:latest
    container_name: db_go_pg
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - DATABASE_HOST=${POSTGRES_DB_HOST}
    ports:
        - '5432:5432'
    volumes:
        - database_postgres:/var/lib/postgresql/data
    networks:
        - go_networks

#  database:
#    image: postgres
#    restart: always
#    env_file:
#      - .env
#    ports:
#      - "5432:5432"
#    volumes:
#      - data:/var/lib/postgresql/data

#  server:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file: .env
#    depends_on:
#      - database
#    networks:
#      - default
#    ports:
#      - "8080:8080"
volumes:
  app:
  database_postgres:

networks:
  go_networks:
    driver: bridge